StrongMind/public-reusable-workflows

.github/workflows/docker-build.yml

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-312)
So that we can self service rails and canvas builds
Create a workflow that can upload to docker and ECR
Will need to be tested on an existing repository.

BEL-312 Docker and ECR build and upload

---

deployment/pyproject.toml
deployment/requirements.txt
deployment/src/strongmind_deployment/container.py
deployment/src/strongmind_deployment/rails.py
deployment/src/tests/mocks.py
deployment/src/tests/test_container.py
deployment/src/tests/test_rails.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-890)
In order to run rails app, the database endpoint must be available in the container.
Pass the database endpoint to the container via environment variables.
Will test with frozen desserts.

BEL-890 Add RDS to container environment

---

deployment/pyproject.toml
deployment/src/strongmind_deployment/container.py
deployment/src/strongmind_deployment/rails.py
deployment/src/tests/mocks.py
deployment/src/tests/shared.py
deployment/src/tests/test_rails.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-916)
ECS container needs access to RDS database
Add firewall rule that allows communication between security groups
Ran pulumi on frozen-desserts-stage

BEL-916 Create firewall rule to allow ECS to hit RDS

---

deployment/src/strongmind_deployment/container.py
deployment/src/strongmind_deployment/rails.py
deployment/src/tests/test_container.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-897)
Logs should be easy to find.
Use pulumi to name resources.
Locally with frozen desserts.

BEL-897 Name stuff so logs are easier to find

---

deployment/src/strongmind_deployment/container.py
deployment/src/tests/mocks.py
deployment/src/tests/test_container.py
deployment/src/tests/test_rails.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-893)
Need HTTPS for our deployments for security.
Add cert managed by AWS.
Ran locally with frozen desserts.

BEL-893 Add SSL

---

.github/workflows/docker-build.yml
.github/workflows/rails-deploy.yml
README.md
docs/rails-app-deployment.md

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-945)
Doc describing how to add deployment to a rails app, and separate build/deploy workflows
Markdown, construct container image in deploy job
Frozen desserts

BEL-945 Initial draft of how to deploy rails doc and separate build/deploy workflows

---

docs/rails-app-deployment.md
docs/slack-release-notification.md

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-954)
Instructions for adding slack notification 
Markdown.
n/a

BEL-954 Instructions for adding slack notification

---

deployment/src/strongmind_deployment/container.py

https://strongmind.atlassian.net/browse/DEVOPS-8912
Update ECS IAM policy on pulumi deploys for tag propagation to tasks

[DEVOPS-8912] Add task and execution roles with common policy

---

deployment/pyproject.toml
deployment/src/strongmind_deployment/container.py

https://strongmind.atlassian.net/browse/DEVOPS-8912
Update ECS IAM policy on pulumi deploys for tag propagation to tasks.

[DEVOPS-8912] Correct the names for execution role and policy

---

deployment/pyproject.toml
deployment/src/strongmind_deployment/container.py

https://strongmind.atlassian.net/browse/DEVOPS-8912
Update ECS IAM policy on pulumi deploys for tag propagation to tasks.

[DEVOPS-8912] Move taskDefinitionArgs to taskDefinition

---

deployment/pyproject.toml
deployment/src/strongmind_deployment/container.py

https://strongmind.atlassian.net/browse/DEVOPS-8912
Update ECS IAM policy on pulumi deploys for tag propagation to tasks.

[DEVOP-8912] Revert some changes to make test passed

---

deployment/pyproject.toml

Raise up python project version to 1.0.11
Test on Repository-Dashboard container

[DEVOPS-9181]  Raise up python project version to 1.0.11

---

deployment/src/strongmind_deployment/container.py
deployment/src/tests/mocks.py
deployment/src/tests/test_container.py

Reverts StrongMind/public-reusable-workflows#22

Revert "[DEVOPS-9181] Create prototype secrets retrieving into container definition secrets block"

---

deployment/pyproject.toml

Raise project version to 1.0.12
Test on Repository-Dashboard container

[DEVOPS-9181] Raise project version to 1.0.12

---

deployment/src/strongmind_deployment/container.py

Change secretsmanager secret name to more unique
On STAGE for Frozen-Desserts
(show before/after of the change if possible)

[DEVOPS-9181] Change secretsmanager secret name to more unique

---

deployment/pyproject.toml
deployment/src/strongmind_deployment/container.py

Change secretsmanager secretVersion content
On STAGE for Frozen-Desserts
(show before/after of the change if possible)

[DEVOPS-9181] Change secretsmanager secretVersion content

---

deployment/src/strongmind_deployment/dynamo.py
deployment/src/strongmind_deployment/rails.py
deployment/src/tests/mocks.py
deployment/src/tests/test_dynamo.py
deployment/src/tests/test_rails.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-1314)
So that an application can host data in dynamo tables
Create a dynamo table component
Unit testing

BEL-1314 Create dynamo component

---

.github/workflows/rspec-test.yml
docs/rspec-test.md

[Link to Jira ticket](https://strongmind.atlassian.net/browse/DEVOPS-9501)
Teams should have an easy way to implement rspec testing into github actions
Create a reusable workflow that teams and reference.
Committing files to main so that I can test on repository dashboard.

Devops 9501 - rspec testing reusable workflow

---

deployment/src/strongmind_deployment/container.py
deployment/src/strongmind_deployment/rails.py
deployment/src/strongmind_deployment/secrets.py
deployment/src/tests/mocks.py
deployment/src/tests/test_container.py
deployment/src/tests/test_rails.py
deployment/src/tests/test_secrets.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-912)
Found a few things that didn't quite work around secrets when testing the new deployment with canvas-docker.
Give AWS the right role to access secrets, and use the right syntax (::).
Unit tests.
Ran locally with canvas-docker.

BEL-912 Get secrets working

---

.github/workflows/rspec-test.yml

[Link to Jira ticket](https://strongmind.atlassian.net/browse/DEVOPS-9501)
Setup a connected postgres and ruby environment for rspec testing
Use github actions container environment so that we are able to test on a ruby container as if it was deployed. 
Merging or order to do testing.

Changed rspec test to run in container for ruby and postgres

---

deployment/pyproject.toml
deployment/src/strongmind_deployment/rails.py
deployment/src/strongmind_deployment/storage.py
deployment/src/tests/mocks.py
deployment/src/tests/shared.py
deployment/src/tests/test_rails.py
deployment/src/tests/test_storage.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-1352)
For Canvas, we need a public readable bucket.
Use bucket components in pulumi (followed example at https://www.pulumi.com/registry/packages/aws/api-docs/s3/bucketaclv2/)
Unit tests. Ran locally.

BEL-1352 Add storage option to get S3 bucket

---

deployment/pyproject.toml
deployment/requirements.txt
deployment/src/strongmind_deployment/container.py
deployment/src/strongmind_deployment/execution.py
deployment/src/strongmind_deployment/rails.py
deployment/src/tests/conftest.py
deployment/src/tests/mocks.py
deployment/src/tests/test_execution.py
deployment/src/tests/test_rails.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-1377)
So that migrations happen for production deployments, run migrations, and fail to deploy if migrations fail to run.
Create a zero-instance service, and using the standard container, run a task with a migration entry point.
Tested with the frozen-desserts test app.

BEL-1377 Run migrations with rails deployments.

---

deployment/pyproject.toml
deployment/src/strongmind_deployment/container.py
deployment/src/tests/test_container.py

[Link to Jira ticket](https://strongmind.atlassian.net/jira/software/c/projects/BEL/boards/598?modal=detail&selectedIssue=BEL-1573)
Adjust default Autoscaling to be more consistent and not fire on deployments
Changed triggers from Maximum to Average and set default max_capacity to 1
Tested on Frozen Desserts Prod

BEL-1573 Adjust scale up metrics

---

deployment/src/tests/test_rails.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-1335)
This test class is too massive to want to add more to, so we need to fix that, because we're adding more to the workers tests as part of this ticket.
Refactoring so rails component fixtures can be used in a `@behaves_like`.
Unit tests

(S) BEL-1335 refactor to re-use spec

---

deployment/pyproject.toml
deployment/src/strongmind_deployment/rails.py
deployment/src/tests/test_rails.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/PWN-246)
To enable the query editor in the AWS console
Enable Data API
Tried this out in the console.

(B) PWN-246 Turn on data API

---

.github/workflows/aws-deploy.yml
.github/workflows/docker-build.yml

Update workflows with new aws action to replace v1 with v4

Update workflows with new aws action

---

.github/workflows/rspec-test.yml

[Link to Jira ticket](https://strongmind.atlassian.net/browse/SKNK-1633)
@maxamus123 is putting a jest test into course builder to validate the behavior of a stimulus controller. This ensures that the build will fail if we break the stimulus controller.
Check for the existence of `jest.config.js` and if it exists, run `npm run test`
Ran command locally.

SKNK-1633 Run jest if it is configured

---

.github/workflows/docker-build.yml
.github/workflows/rspec-test.yml
scripts/parse_rspec_json_output.py

[[Link to Jira ticket](https://strongmind.atlassian.net/browse/DEVOPS-13059)](https://strongmind.atlassian.net/browse/TEAM-NUMBER)
Fail build if test run includes skipped tests without a developer provided reason
Add action to output the rspec results to a json file.
Add action to parse the results and return a failing exit code if skipped tests match a specific pattern.
Tested on a branch using repo dashboard
With skipped tests:
No tests skipped:
Still outputting test results to console:

Fail build if test run includes skipped tests without a developer provided reason

---

.github/workflows/aws-deploy.yml
.github/workflows/docker-build.yml
deployment/src/strongmind_deployment/rails.py
deployment/src/tests/test_rails.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/devops-13124)
Use S3 and Cloudfront for our assets in our Rails apps
Implemented gem 'fog-aws' and gem 'asset_sync'
removed assets:precompile from dockerfile
added assets:precompile to migration container
https://github.com/StrongMind/repository-dashboard/pull/185
tested locally, verified assets are uploaded to s3 and app functions normally

Devops 13124

---

.github/workflows/pulumi.yml

https://strongmind.atlassian.net/browse/EXCAY2-7

remove black as it is causing issue

---

deployment/src/strongmind_deployment/cloudfront.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/DEVOPS-13609?atlOrigin=eyJpIjoiMzNmZGFiNjRkYjE1NGExMTk3NWY0NzU4ODMyNDNjNjgiLCJwIjoiaiJ9)
Fix CORS issues from Rails apps or whatever alternate domains our issue will pop in
Added CORS s3 bucket policy, also added s3 caching to Cloudfront.
I modified cloudfront.py in stage cdn manually and deployed the changes to be sure everything works in stage.

Adding s3 CORS policy, also adding s3 cache to Cloudfront

---

deployment/pyproject.toml
deployment/src/strongmind_deployment/acm.py
deployment/src/strongmind_deployment/route53_zone.py

https://strongmind.atlassian.net/browse/EXCAY2-44?atlOrigin=eyJpIjoiNjlmODVkYjhkNzY2NGI4NGFiODg0NWNkMjVmNTI3Y2EiLCJwIjoiaiJ9

Module to create Route53 zone

---

deployment/src/strongmind_deployment/acm.py

to fix function calls before cert outputs became available and to remove redundant codes
remove lines of code not in use.
use the apply method to wait for outputs to become available at runtime
deployed from shared-infrastructure to ensure the code is working.

Excay2 65 acm

---

.github/workflows/aws-deploy.yml
deployment/src/strongmind_deployment/cloudfront.py
deployment/src/strongmind_deployment/container.py
deployment/src/strongmind_deployment/rails.py
deployment/src/strongmind_deployment/redis.py
deployment/src/strongmind_deployment/secrets.py
deployment/src/strongmind_deployment/storage.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/devops-13637)
Add owner tag to public reusable deployments resources
Creating tag from codeowners file
Ran locally, pululmi up on repo dashboard, verified tags applied

Add owner tag to public reusable deployments resources

---

deployment/src/strongmind_deployment/container.py
deployment/src/strongmind_deployment/rails.py
deployment/src/strongmind_deployment/redis.py
deployment/src/strongmind_deployment/secrets.py
deployment/src/strongmind_deployment/storage.py
deployment/src/tests/test_storage.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/devops-13637)
Add owner tag based on codeowners file
Changed how we path to the file to get tests to pass
verified locally, tests pass

Add subprocess module to retrieve file path from git repository

---

deployment/src/strongmind_deployment/rails.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/devops-13852)
Adding 'NAMESPACE' var to the ecs container that can be used when publishing custom metrics to cloudwatch
Added key 'namespace' to addtional_env_vars using project_stack as the value

Adding 'NAMESPACE' var to the ecs container

---

deployment/src/strongmind_deployment/dashboard.py
deployment/src/strongmind_deployment/rails.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/devops-11389)
Deploy Dashboard as Part of Standard Ruby On Rails App Deploy
Creating dashboard.py with a dashboard component and adding to rails.py
Modified strongmind deployment package locally in repo-dashboard and pulumi deployed

Creating dashboard.py with a dashboard component and adding to rails.py

---

deployment/src/strongmind_deployment/batch.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/DEVOPS-14055)
Batch needs IAM permissions to call other services from batch service linked role.
Change IAM policy in batch.py... it needs to be better. But it will work for now. 
Tested the policy in etls repo.. it works.

iam changes

---

deployment/src/strongmind_deployment/vpc.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/EXCAY2-212)
This should have been in this code from the start but was missed when adding the VPC Endpoints.
It was missed in testing because Pulumi somehow configured the default VPC Security group differently in the stage account vs the strongmind_main account.   This is still being investigated.
The stage account security group had an open ingress rule,  where the main account had only a self referencing security group - to allow internal traffic only.
VPC Endpoints are now given TLS ingress, which fixes a bug where the VPC Endpoint is unable to talk to native AWS Hosted services like secrets manager, and KMS. 
Tested in the stage account.

Add HTTPS ingress to VPC Endpoints

---

.github/workflows/aws-deploy-with-pulumi.yml
.github/workflows/aws-deploy.yml
deployment/src/strongmind_deployment/batch.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/DEVOPS-14437)
Teams should be able to run 'pulumi down' from a ci system.
In our ci yamls, 'pulumi up' is now 'pulumi $input' 
Tested in branch

Devops 14437 - Pulumi accepts $input

---

deployment/src/strongmind_deployment/container.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/devops-14567)
Add bedrock to course builder, and in turn all apps using the reusable
Changed the task policy to have the new permissions
Will test and verify in course builder stage

Adding bedrock InvokeModel and InvokeModelWithResponseStream to task policy

---

deployment/src/strongmind_deployment/container.py
deployment/src/tests/test_container.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/devops-14617)
Update PRW for task policy to have cloudwatch access.
Add logs: to task policy
Update test, tests pass

Add logs: to container task policy

---

deployment/src/strongmind_deployment/autoscale.py
deployment/src/strongmind_deployment/container.py
deployment/src/strongmind_deployment/rails.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/devops-11388)
Fix worker autoscaling
Change the name of the kwarg used to call and passed to the container component
Differentiate method names in autoscale.py
Applied changes to library in local repository dashboard and pulumi deployed

Fix worker autoscaling

---

deployment/src/strongmind_deployment/batch.py
deployment/src/tests/mocks.py
deployment/src/tests/test_batch.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/devops-14055)
Add unit test cases for batch.py file
Look at other test files in the test directory to come up with different unit test cases
Ran pytest on the whole test suite with 100% test pass rate

Create tests for ECS batch component

---

deployment/src/strongmind_deployment/batch.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/devops-13886)
changes to batch.py to get etls-prod batch to run on a schedule; was previously incorrectly configured
in the event target: use definition name for job_name; use the execution role for role_arn
Made changes using AWS console, verified good schedule run, matching changes in code

Devops-13886 changes to batch.py

---

deployment/src/strongmind_deployment/autoscale.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/bel-2964)
Adjust step scaling for workers, setting a baseline as we implement worker autoscaling in course-builder.
set step scaling to scale 1 container on metric of 0-100 and 3 containers on metric greater than 100
Autoscaling has been tested in repo-dashboard

Adjust step scaling for workers

---

.github/workflows/publish-gem.yml

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-3145)

BEL-3145: Replace velocityCheckin with notify_deployment

---

deployment/src/strongmind_deployment/rails.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-3521)
We did this manually in central, and need to support scaling everywhere.
Make max 128.

BEL-3521 Scale up RDS to max 128

---

README.md

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-3386)
We want the developers to be able to tear down an infrastructure if needed. 
Add documentation on how to delete infrastructure in AWS in README

BEL-3386: Add documentation on how to destroy infrastructure for a repository in README.md

---

.github/workflows/commit-info.yml
.github/workflows/docker-build.yml
scripts/process-commits.sh

[Link to Jira ticket](https://strongmind.atlassian.net/browse/pwn-1383)
Publish commits to repo dashboard
Add Commit Script and Workflow to push commits to repo dash
testing after this merge

PWN-1383 Add Commit Script and Workflow to push commits to repo dash

---

.github/workflows/commit-info.yml

[Link to Jira ticket](https://strongmind.atlassian.net/browse/pwn-1383)
Fix Workflow to allow workflow to be a called workflow
Fix Workflow to allow workflow to be a called workflow

PWN-1383 Fix Workflow to allow workflow to be a called workflow

---

.github/workflows/commit-info.yml

[Link to Jira ticket](https://strongmind.atlassian.net/browse/PWN-1383)
Fix workflow to add script into running workflow
Download script into runner
testing now

(B) PWN-1383 Download script into runner

---

deployment/src/strongmind_deployment/container.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/bel-3787)
Fix Healthy Host Metric Alarm
New load balancer configs deploy targets to 3 diff avail zones and we need to pull new metrics from each zone and do math.
Ran pulumi locally on repo dashboard and verified alarm is configured properly.

Bel-3787 Fix Healthy Host Metric Alarm

---

deployment/src/strongmind_deployment/container.py
deployment/src/tests/mocks.py
deployment/src/tests/test_container.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-3811)
We need to alarm on unhealthy hosts
Create an alarm for unhealthy hosts
Add test cases for healthy and unhealthy hosts alarm
Pytest

BEL-3811: Alarm on Unhealthy Hosts

---

deployment/src/strongmind_deployment/container.py
deployment/src/tests/test_container.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/bel-3811)
Add Unhealthy Host Metric Alarm
- Alarm when unhealthy hosts are more than 25% of the desired count of hosts
Deployed pulumi locally on repo-dashboard

Bel-3811 Add Unhealthy Host Metric Alarm

---

deployment/src/strongmind_deployment/container.py
deployment/src/tests/test_container_autoscaling.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/bel-3932)
Replace running task alarm 
Replace running task alarm and set threshold to 25

Bel-3932 Replace running task alarm and set threshold to 25

---

deployment/src/strongmind_deployment/container.py
deployment/src/tests/test_container_autoscaling.py

Update Running Task Alarm to be based on Anomoly Detection 
Create new alarm based on anomoly detection with a band of 50
Add devops opsgenie to the alarm
Create new tests for new alarm
Pushed locally with repo dash and verified alarm

Bel 3937 Update Running Task Alarm to be based on Anomoly Detection 

---

deployment/src/strongmind_deployment/container.py
deployment/src/strongmind_deployment/rails.py
deployment/src/tests/mocks.py
deployment/src/tests/test_container_autoscaling.py
deployment/src/tests/test_worker_container_autoscaling.py

Most apps should autoscale, so we want this on by default.
- Make default True in the rails component for worker_autoscale.
- Bring back sns_topic_arn tests
RSpec

BEL-3425 Turn on worker autoscaling by default

---

deployment/src/strongmind_deployment/dynamo.py
deployment/src/tests/test_container_autoscaling.py
deployment/src/tests/test_dynamo.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-3135)
Namespace all dynamodb tables
Add namespace to dynamo component 
Add tests
Pytest

BEL-3135 Namespace dynamo

---

deployment/src/strongmind_deployment/alb.py
deployment/src/strongmind_deployment/container.py
deployment/src/strongmind_deployment/rails.py
deployment/src/strongmind_deployment/redis.py
deployment/src/strongmind_deployment/storage.py
deployment/src/strongmind_deployment/util.py
deployment/src/strongmind_deployment/worker_autoscale.py
deployment/src/tests/test_redis.py
deployment/src/tests/test_util.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-3135)
Rename ALL Pulumi components so that we can have only one stack for canvas
Rename all pulumi components
pulumi preview on canvas-docker for testing
pulumi preview on repo-dash to verify no breaking changes

BEL-3135 Rename pulumi components

---

deployment/src/strongmind_deployment/lambda_component.py
deployment/src/tests/test_lambda.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/Bel-2966)
Add a reusable lambda component and use it to deploy snow-stream-alert
Add new component and tests
Tests pass
Deployed snow-stream-alert lambda locally

Bel 2966 Add Lambda Component

---

.github/workflows/docker-build.yml
.github/workflows/rspec-test.yml

Our builds take way too long.
Some of our rails apps have [this gem](https://github.com/grosser/parallel_tests) and it works. This allows us to use it in the build.
Will have to test once this is merged - hard to test shared github workflows.

BEL-3173: Add support for running tests in parallel

---

.github/workflows/rspec-test.yml

Ran into an issue with a never ending build when trying to seed the parallel dbs.
Don't seed.

BEL-3173: Only setup schema, don't seed for tests

---

.github/workflows/rspec-test.yml

See https://flipswitch.slack.com/archives/C04HF4JQB8C/p1730420157900829
See https://flipswitch.slack.com/archives/C04HF4JQB8C/p1730420157900829

BEL-3173: Try using macos for test runs

---

.github/workflows/rspec-test.yml

Faster test runs
Highest non-M1 version

BEL-3173: Try using macos-13 for test runs

---

.github/workflows/rspec-test.yml

MacOS doesn't have docker.
Install docker using instructions here: https://stackoverflow.com/a/76490257

BEL-3173: Install docker

---

.github/workflows/rspec-test.yml

Speed up test runs.
Try running test folders in separate jobs.
Local testing with act.

BEL-3173: Try running tests in a job per folder

---

.github/workflows/docker-build.yml

Faster test runs.
Enable access to approach in previous PR.

BEL-3173: Enable running of tests in a job per folder

---

.github/workflows/rspec-test.yml

Faster builds
Get the input correctly

BEL-3173: Get the input correctly

---

.github/workflows/rspec-test.yml

Make builds faster.
Split files under spec/models into 4 subfolders evenly.
Ran locally
This needs to wait until these PRs are completed:
https://github.com/StrongMind/course-builder/pull/1373
https://github.com/StrongMind/central/pull/1607

BEL-3173: Distribute files under spec/models into 4 subfolders

---

.github/workflows/rspec-test.yml

Faster builds.
Fix bash script.
Tested with https://github.com/nektos/act/

BEL-3173: Fix folder split script for ubuntu

---

.github/workflows/rspec-test.yml

Faster builds.
Distribute models specs in the test job.

BEL-3173: Add distribute script to step that runs the test

---

deployment/src/strongmind_deployment/container.py
deployment/src/strongmind_deployment/rails.py
deployment/src/tests/test_container.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-4204)
More changes to move canvas to common infrastructure
- Build s3 policy despite storage=false
- Namespace the certificate
- Some ignore changes for cluster and clusterinstance
All changes have been used to deploy new-id-sandbox and cdcr locally

Bel 4204 More Changes to Move Canvas to Common Infrastructure

---

.github/workflows/aws-deploy-with-pulumi.yml
.github/workflows/aws-deploy.yml
.github/workflows/docker-build.yml
.github/workflows/rspec-test.yml

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-3174)
Improve build times
Use larger runners for build, test, and deploy
Larger runners on canvas improved build times by 10min (30%)
Tested on repo dashboard improved build time by 1 min (20%)

Bel-3174 Implement Larger Runners for Common Rails Infrastructure

---

.github/workflows/rspec-test.yml

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-4476)
Faster builds. 
Run specs in parallel within the folders. Should get some gains now that we are running in larger runners.
Ran inside course builder with nektos/act

BEL-4476: Run in parallel inside folders

---

.github/workflows/rspec-test.yml

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-4476)
Previous PR put a "./" in the command which resulted in 0 tests running.
Use bash to remove the leading ./
Local testing

BEL-4476: Fix folder name issue

---

.github/workflows/rspec-test.yml

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-4476)
Hitting issue with redis that was unexpected.
Go back to just running the specs in the folder.

BEL-4476: Revert parallel attempt

---

.github/workflows/rspec-test.yml

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-4476)
Save 4 seconds.
Skip unnecessary step.

BEL-4476: Do not attempt to start postgres again when it is already running

---

deployment/src/strongmind_deployment/container.py
deployment/src/tests/test_container.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-3432)
Tag resources
Add tags to alarms for the container
Deployed on repo-dashboard locally

BEL-3432 Add tags to alarms

---

deployment/src/strongmind_deployment/worker_autoscale.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-3136)
Allow canvas workers to autoscale
Update namespace and dimensions to allow for canvas
Deployed locally with pulumi on new-id-sandbox
Tested it scales in production

BEL-3136 Update namespace and dimensions to allow for canvas

---

deployment/src/strongmind_deployment/container.py
deployment/src/strongmind_deployment/rails.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-4581)
More changes to allow for canvas deploys
- Fix dashboard to use a unique name for the pulumi resource
- ignore changes for 'threshold' for the container autoscaling out alarm
Deployed with pulumi locally

BEL-4581 More changes to accomodate canvas deploys

---

.github/workflows/dev_upload_interactives.yml

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-4757)
Address issue where files are being uploaded to a new folder
remove trailing '/'
Files are going to `no_name`

BEL-4757 Trying to fix where files are uploaded

---

.github/workflows/dev_upload_interactives.yml

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-4757)
Fix issue where files are being uploaded to wrong path
rewrite az command

Bel 4757 fix local of upload

---

deployment/src/strongmind_deployment/container.py
deployment/src/tests/test_container.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/RD-801)
We need permission to list models so that we can support new models as they come out.
Give permission.

(B) RD-801: Add bedrock:ListInferenceProfiles permission to task role

---

deployment/src/strongmind_deployment/container.py
deployment/src/tests/test_container.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-14561)
We need to add email role policies to be able to use Amazon's Simple Email Service.
Add SendEmail and SendRawEmail role policies.

QTY-14561: Add email role policies

---

README.md

This pull request includes an update to the `README.md` file to introduce a new AI assistant, Palumi King, and provide instructions on how to regenerate AI-generated documentation. The most important changes include the addition of a new section about the AI assistant and detailed steps for regenerating the AI-generated documentation.
* Introduced Palumi King, an AI assistant designed to help with StrongMind infrastructure, including guidance on AWS services, Infrastructure as Code using Pulumi, CI/CD workflows, troubleshooting, and security strategies.
* Added detailed steps to regenerate AI-generated documentation using specific prompts and contexts.
[Talking to AI Assistant](https://chatgpt.com/g/g-67bcb0b91c388191a2812a788901a882-palumi-king)

Added AI assistant documentation

---

.github/workflows/rspec-test.yml

[Link to Jira ticket](https://strongmind.atlassian.net/browse/RD-1091)
Faster test runs.
Distribute files in subfolders evenly.
Ran script locally.

RD-1091: Distribute files more evenly

---

deployment/src/strongmind_deployment/container.py
deployment/src/tests/test_container.py

[Link to Jira ticket](https://strongmind.atlassian.net/browse/SKNK-7085)
Would like to be able to refresh models in production.
Give permission to list foundation models.
Updated pytest

SKNK-7085: Give permission to list models
