StrongMind/public-reusable-workflows

- .github/workflows/rails-deploy.yml
- deployment/requirements.txt
- deployment/src/strongmind_deployment/container.py
- deployment/src/strongmind_deployment/rails.py
- deployment/src/tests/test_container.py
- deployment/src/tests/test_rails.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-899)
Provide a friendly "name.strongmind.com" URL to apps out-of-the-box.
Use pulumi_cloudflare to create CNAME record pointing to the load balancer DNS name.
Ran locally with frozen desserts. (http://stage-frozen-desserts.strongmind.com/)
> BEL-899 Add cname to cloudflare

- deployment/pyproject.toml
- deployment/src/strongmind_deployment/container.py
- deployment/src/tests/test_container.py
Noticed this when looking at course-builder deployment. If we redirect on the root / the health check fails and the image is never updated.
Use /up for the health check.
Unit tests.
> Use /up for health check

- .github/workflows/docker-build.yml
We've hit an issue a lot where it appears that a build is deployed but then ECS fails when it attempts to spin up the container.
Build and run container locally to make sure it starts up before pushing it to ECR.
Tried this out in https://github.com/StrongMind/course-builder/blob/main/.github/workflows/build.yml
> Block pushing new containers if they don't start up

- .github/workflows/dotnet-build.yml
https://strongmind.atlassian.net/browse/DEVOPS-6963
Migrate eventgrid-viewer-blazor Build and Release Pipeline from Azure DevOps to GitHub Actions
Add Dotnet build configuration for public repos usage
No need
No need
> [DEVOPS-6963] Add Dotnet build configuration for public repos usage

- .github/workflows/deploy-dev-dotnet-webapp.yml
https://strongmind.atlassian.net/browse/DEVOPS-6963
Migrate eventgrid-viewer-blazor Build and Release Pipeline from Azure DevOps to GitHub Actions
Add Dotnet app deploy configuration for public repos usage
No need
No need
> [DEVOPS-6963] Add Dotnet app deploy configuration for public repos usage

- .github/workflows/rails-deploy.yml
[SKNK-411](https://strongmind.atlassian.net/browse/SKNK-411)
To use Sidekiq-Pro, we need to set an environment variable
Set the BUNDLE_GEMS__CONTRIBSYS__COM from the org secret in GitHub
No testing was done
N/A
[SKNK-411]: https://strongmind.atlassian.net/browse/SKNK-411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (B) SKNK-411: Add env variable for rails deploys for sidekiq pro

- deployment/src/strongmind_deployment/container.py
- deployment/src/tests/mocks.py
- deployment/src/tests/test_container.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/DEVOPS-8912)
AWS billing information for ecs is based on the running tasks. 
Configure the ecs service to propagate the tags to the tasks
Ran configuration on global build to test the functionality. Applied same changes to the rails component. 
(show before/after of the change if possible)
> add tag propagation and tests to ecs tasks.

- deployment/requirements.txt
- deployment/src/strongmind_deployment/rails.py
- deployment/src/strongmind_deployment/redis.py
- deployment/src/tests/mocks.py
- deployment/src/tests/test_rails.py
- deployment/src/tests/test_redis.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-934)
We need to support the use of Redis as either a queue (for Sidekiq) or as a cache, because the best settings (maxmemory-policy) differ in these two scenarios.
Provide a CacheComponent and QueueComponent that can be included in the RailsComponent by simply passing queue_redis=True and/or cache_redis=True as parameters. You can also provide an entire component in these parameters if you need to scale the Redis up.
Unit tests.
Integration tested with the frozen-desserts test application.
> BEL-934 Add redis queue/cache components

- deployment/src/strongmind_deployment/container.py
- deployment/src/tests/mocks.py
- deployment/src/tests/test_container.py
Create prototype secrets retrieving from ssecretmanager
Test on Repository-Dashboard container
> [DEVOPS-9181] Create prototype secrets retrieving into container definition secrets block

- deployment/src/strongmind_deployment/container.py
- deployment/src/tests/mocks.py
- deployment/src/tests/test_container.py
Create prototype secrets retrieving from ssecretmanager
Test on Repository-Dashboard container
> [DEVOPS-9181] Canvas Enterprise Deploy: Retrieve Secrets

- deployment/pyproject.toml
- deployment/src/strongmind_deployment/container.py
- deployment/src/strongmind_deployment/rails.py
- deployment/src/strongmind_deployment/secretsmanager.py
- deployment/src/tests/mocks.py
- deployment/src/tests/test_container.py
- deployment/src/tests/test_rails.py
- deployment/src/tests/test_secretsmanager.py
https://strongmind.atlassian.net/browse/DEVOPS-9495
Create only one secretsmanager per environment in public-reusable-workflow
Write separate resource component to work with the secretsmanager
Write tests for new secretsmanager component
Locally on Frozen Desserts
TaskDefinition revision 21 (with empty secrets)
TaskDefinition revision 22 (with test secrets)
> [DEVOPS-9495] Create only one secretsmanager per environment in public-reusable-workflow

- deployment/pyproject.toml
- deployment/src/strongmind_deployment/rails.py
- deployment/src/tests/shared.py
- deployment/src/tests/test_rails.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-1353)
For Canvas, we are on old ubuntu base images that don't support the latest postgres libraries, so we need to use MD5 hashed passwords rather than SCRAM. This should enable that option.
Optionally set the master password to the MD5 hashed version of the actual password.
Unit tests.
Tried it with frozen desserts - was able to connect via Data Grip with the option on or off using the same password.
> BEL-1353 Provide option to use md5 hashed postgres passwords

- deployment/src/strongmind_deployment/container.py
- deployment/src/strongmind_deployment/rails.py
- deployment/src/tests/test_container.py
- deployment/src/tests/test_rails.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-1369)
While I think we want to standardize on `/up` for everything moving forward, canvas uses `/health_check` - perhaps we should just change canvas but for now I'm thinking this option is reasonable.
Allow a `custom_health_check_path` to be passed to the RailsComponent (or ContainerComponent).
Unit tests. Testing with stage-canvas.
> BEL-1369 Allow projects to have a custom health check path

- .github/workflows/aws-deploy.yml
- deployment/pyproject.toml
- deployment/src/strongmind_deployment/rails.py
- deployment/src/tests/test_rails.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-1403)
For canvas, we need a separate worker container name.
If there is an environment variable called "WORKER_CONTAINER_IMAGE" we use that for the worker.
Will test with canvas.
> BEL-1403 Allow worker container override by env var

- deployment/pyproject.toml
- deployment/src/strongmind_deployment/rails.py
- deployment/src/tests/test_rails.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/DEVOPS-9613)
Ensure that RDS databases are taking snapshots and that they make a final snapshot upon deletion.
Final snapshot was already in place, updated the retention to be 14 days (changeable) as the default was 1 day. 
Pytest passed the code changes. Also tested on CMS using global build with no issues.
> Devops 9613 rds snapshot retention

- deployment/pyproject.toml
- deployment/src/strongmind_deployment/rails.py
- deployment/src/tests/test_rails.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-1439)
So that we can migrate canvas instances, allow database clusters to be restored from cluster snapshots
Send a `snapshot_identifier` sent to the RailsComponent to its RDS cluster
Unit tests
> Bel 1439 allow restore from snapshot

- deployment/pyproject.toml
- deployment/src/strongmind_deployment/container.py
- deployment/src/strongmind_deployment/rails.py
- deployment/src/tests/test_container.py
- deployment/src/tests/test_rails.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-1377)
Some systems (Canvas) need to run specific pieces at deployment (just db:migrate) whereas the default should be prepare/migrate/seed.
Default to prepare/migrate/seed and allow keyword argument to override.
Unit tests.
> BEL-1377 Allow overriding execution entry point

- deployment/src/strongmind_deployment/rails.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-1439)
When deploying after a snapshot restore, the database name and master username changes. Attempting to correct this requires a recreation of the database cluster.
This ignores these changes so that we don't attempt to recreate the database.
Ran locally.
> BEL-1439 Ignore database name and master username changes

- deployment/README.md
- deployment/src/strongmind_deployment/rails.py
- deployment/src/tests/test_rails.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-1377)
Migrations with parameters to work with Enterprise canvas
Change things to take in parameters to be overridden from default to accommodate canvas names. Change to apply immediately for changes to databases.
Unit tests and acceptance tested against canvas staging environment.
> Bel 1439 complete migrations for canvas

- deployment/src/strongmind_deployment/container.py
- deployment/src/strongmind_deployment/rails.py
- deployment/src/tests/test_container.py
- deployment/src/tests/test_rails.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-1474)
In order to evaluate the current state of jobs/workers, we need a way to parse CloudWatch logs.
Use log metric filters to parse the logs.
Added filters to frozen-desserts.
> BEL-1474 Add ability to specify log metric filters

- deployment/pyproject.toml
- deployment/src/strongmind_deployment/container.py
- deployment/src/strongmind_deployment/rails.py
- deployment/src/tests/test_container.py
- deployment/src/tests/test_rails.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-1382)
So that we can continue serving traffic under load, when the web servers are at high CPU utilisation, scale up the number of containers running.
Use pulumi to set up auto scaling targets, policies and alarms.
Tested in canvas stage, will test with frozen desserts.
> BEL-1382 Enable auto scaling upwards for web

- deployment/pyproject.toml
- deployment/src/strongmind_deployment/container.py
- deployment/src/tests/test_container.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-1382)
Include dimensions for the alarm so that they are tied to the cluster for the use of autoscaling.
Added in the autoscaling method. Unit tested.
Unit tested and tested against canvas-stage and frozen-desserts.
> BEL-1382 Dimensions for autoscaling alarm

- deployment/pyproject.toml
- deployment/src/strongmind_deployment/rails.py
- deployment/src/strongmind_deployment/storage.py
- deployment/src/tests/test_storage.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/DEVOPS-10396)
To default s3 buckets to private and allow override to set the bucket to public
Set storage key default to True to make the bucket private
Added new kwarg to allow the bucket to be public
Added test for new kwarg in storage
Ran tests and they passed
> S3 storage options for deployment

- deployment/pyproject.toml
- deployment/src/strongmind_deployment/container.py
- deployment/src/tests/mocks.py
- deployment/src/tests/test_container.py
- deployment/src/tests/test_container_autoscaling.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-1378)
When we have scaled out horizontally because of CPU usage too high, we also need to scale in because of usage that is too low.
Use the same policies/alarms we used for scale out, but scale in at an average usage of under 50% over 5 minutes.
Ran frozen-desserts-prod deployment locally.
Before:
After:
> BEL-1378 Scale in for web

- deployment/pyproject.toml
- deployment/src/strongmind_deployment/rails.py
- deployment/src/tests/test_rails.py
Hit this when running pulumi destroy on frozen-desserts-stage
Set a final snapshot identifier so that AWS can take a final snapshot when removing an environment.
Ran on frozen desserts and it set properly.
> Set final snapshot identifier

- .github/workflows/rspec-test.yml
When setting up new apps, we have not said that reporting code coverage is REQUIRED for deployment. But this step currently enforces that.
Only report code coverage if the CC_TEST_REPORTER_ID secret is in place for the repo.
Used code from https://stackoverflow.com/questions/70249519/how-to-check-if-a-secret-variable-is-empty-in-if-conditional-github-actions
> Skip reporting coverage if we don't have it in place for the repo

- deployment/pyproject.toml
- deployment/src/strongmind_deployment/rails.py
- deployment/src/tests/test_rails.py
- deployment/src/tests/test_rails_worker.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-1335)
So that we can deploy the canvas workers
Allow `worker_cmd` to be sent to the worker via the rails component. Remove the default entrypoint and move it to the cmd.
Tested using the frozen-desserts repo.
> BEL-1335 Worker cmd override and web cmd default

- deployment/src/strongmind_deployment/container.py
- deployment/src/tests/mocks.py
- deployment/src/tests/test_container.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-1703)
So that we can SSH into the containers and run `rails c`
Turn on `enable_execute_command`
Did this in [central](https://github.com/StrongMind/global-build/commit/5a19b4f2da7ec545f1d92a732d9dfa1fbac83e20) and set it up manually elsewhere.
> (B) BEL-1703 Turn on enable_execute_command

- deployment/src/strongmind_deployment/container.py
- deployment/src/tests/test_container.py
[Link to Jira ticket](https://strongmind.atlassian.net/jira/software/c/projects/BEL/boards/598?selectedIssue=BEL-1668)
Make log metric names unique
Prepend all metrics with project stack name
Canvas Docker Staging
> (B) BEL-1379: Autoscaling Worker

- deployment/src/strongmind_deployment/container.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/DEVOPS-10427)
Migrate repository-dashboard, and every rails app using global build, to strongmind-deployment.
We need to bypass the creation of the DNS record while we stand up side-by-side environments in order to more easily facilitate the migrations. 
Implemented this change locally as we stood up the new repository-dashboard environment.
Ran tests locally.
> Adding option to bypass creation of dns record

- deployment/src/strongmind_deployment/rails.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/DEVOPS-11259)
Add tags to RDS DBInstances b/c repo-dashboard is replacing clusters with instances so we can pull in all instances, not just clustered ones. 
Add tags.tags to self.rds_serverless_cluster_instance
Will verify with a deploy of repository-dashboard
> Add tags to cluster instances

- deployment/src/strongmind_deployment/container.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/DEVOPS-11329)
Strongmind rails deployment should not setup port 3000 on the loadbalancer.
remove the default target group port from the load balancer setup
Ran pytest and all tests passed
Will verify in prod with a deploy of repository-dashboard
> remove the default target group port from load balancer which was setting the port to 3000

- deployment/src/strongmind_deployment/container.py
Reverts StrongMind/public-reusable-workflows#71
> Revert "remove the default target group port from load balancer which was setting the port to 3000"

- deployment/src/strongmind_deployment/container.py
- deployment/src/strongmind_deployment/rails.py
- deployment/src/strongmind_deployment/storage.py
- deployment/src/tests/test_container.py
- deployment/src/tests/test_rails.py
- deployment/src/tests/test_storage.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/DEVOPS-11255)
For RailsComponent with storage=True, setup AWS credentials
Create Iam policy for s3
Attach policy to task role
Added tests for storage, container, and rails changes.
Verified with good pulumi up.
Verified can still access s3 bucket w/o needing access key or id provided in storage yaml.
> creates iam policy and attaches to role; add tests

- deployment/src/strongmind_deployment/container.py
- deployment/src/tests/test_container_autoscaling.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/PLT-9553)
So that containers will scale up quicker, and stay around longer during peridos of heavy load in an effort to reduce 5XX errors.
Decrease scale out cooldown to 15 seconds (from 60) Increase scale in cooldown to 900 seconds (from 60)
unit tests
N/A
> (B) PLT-9553: Modify container scale in/out cooldowns

- deployment/src/strongmind_deployment/rails.py
[[Link to Jira ticket](https://strongmind.atlassian.net/browse/DEVOPS-12510)](https://strongmind.atlassian.net/browse/TEAM-NUMBER)
Rails component accepts input to set database ACU minimum.
Added rds_minimum_capacity and rds_maximum_capacity kwargs
Modified serverlessv2_scaling_configuration
Did not modify tests.
Made changes to repo dashboard and ran pulumi up locally, verified change pushed.
> Option to modify the RDS ACU min and max

- .github/workflows/build-deployment-package.yml
- deployment/pyproject.toml
We have been having issues sourcing this repo in pulumi projects as a git dependency.   Pulumi tries cloning and explodes in doing so. 
It works ok for development, but not in github actions. 
Example: 
https://github.com/StrongMind/shared-infrastructure/actions/runs/8328969113/job/22790798781
trigger python package builds off the `caylent_main` branch, and send them to a new pypi project `strongmind_deployments_beta`.
> deploy strongmind beta

- deployment/src/strongmind_deployment/container.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/devops-13588)
Alarm when ecs healthy host count is less than desired host count.
Added a metric alarm to the load balancer for container.py
Added desired_web_count as the threshold minimum metric
Added sns_topic_arn for the actions.
Currently hardcoded devops-opsgenie sns; we have a future story to make this dynamic based on owning team tag
Ran with pulumi locally and verified metric alarm created
> Alarm when ecs healthy host count is less than desired host count.

- deployment/src/strongmind_deployment/container.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/devops-13588)
Refactor healthy_host_metric_alarm creation in ContainerComponent so that current tests will pass; also use the right dimensions for the LB and TG
Refactored the healthy_host_metric_alarm to use lambda apply for LB and TG arns
Ran pulumi up locally and verified alarm created with corrected dimensions
Tests pass although still seeing this: AttributeError: 'NoneType' object has no attribute 'arn'
Still need to create test for this method, expecting tests to pass in workflow, pushing this as main workflow is broken.
Will create backlog item to add test for this method.
> Refactor healthy_host_metric_alarm creation in ContainerComponent

- deployment/src/strongmind_deployment/container.py
Reverts StrongMind/public-reusable-workflows#90
Blocking teams from deploying.
> Revert "Refactor healthy_host_metric_alarm creation in ContainerComponent"

- deployment/src/strongmind_deployment/container.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/devios-13588)
Use positional args in the metric_alarm instead of promised values
Use positional args in the metric_alarm instead of promised values to allow for 'lazily' applied output
Verified locally with repo dashboard
> Use positional args in the healthy_host_metric_alarm instead of keyword args

- deployment/src/strongmind_deployment/subnet.py
- deployment/src/strongmind_deployment/vpc.py
[EXCAY2-34](https://strongmind.atlassian.net/browse/EXCAY2-34)
The subnet type tag was placed improperly on the original PR, this fixes that.
It also adds a convenience method to allow other modules (specifially for the ecs module in development) to resolve a VPC's subnets by tags.
This will be used by the alb and ecs components (in development).
Example Usage: 
```python
ecs_args = ecs.EcsComponentArgs(
vpc_id=vpc_id,
subnet_placement=vpc.SubnetType.PRIVATE,
```
[EXCAY2-34]: https://strongmind.atlassian.net/browse/EXCAY2-34?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Excay2 34 vpc subnet resolver

- deployment/src/strongmind_deployment/ecs.py
- deployment/src/strongmind_deployment/util.py
This module is intended to be used with an ALB module still in development.
This module requires a lot more consumer level code than the previous container.py, however it uses an atomic component based approach instead of a monolithic Component.  This means that with the AlbComponent, we can compose new service types with this EcsCompoment.
The service repository will still have minimal infrastructure code, if we introduce a concept of "service_types" in this repository, that layers on top of this EcsComponent.  Things to come in the future!
[EXCAY2-33](https://strongmind.atlassian.net/browse/EXCAY2-33)
[EXCAY2-33]: https://strongmind.atlassian.net/browse/EXCAY2-33?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Introduce initial ECS component

- deployment/src/strongmind_deployment/vpc.py
[EXCAY2-34](https://strongmind.atlassian.net/browse/EXCAY2-34)
Private links ensure traffic is travelling within the VPC as opposed to on public networks.  This increases security especially when FERPA is involved.
This also fixes an oversight where the NAT Gateway code was given the private subnet id's, instead of the public ids. :)
we don't have test accounts to test this with, so this PR has already been deployed to the stage account.
[EXCAY2-34]: https://strongmind.atlassian.net/browse/EXCAY2-34?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add private links for increased security.  Fix NAT Gateway

- deployment/src/strongmind_deployment/alb.py
- deployment/src/strongmind_deployment/ecs.py
[EXCAY2-41](https://strongmind.atlassian.net/browse/EXCAY2-41)
Identity required some changes to be successfully deployed.
Changes involved: 
Introduces the Alb component.
* 443 listener
* 80 listener with a default redirect to 443
Changes to ECS component include:
* no longer defaulting healthcheck path to "/up"
* type changes to container configuration
* exposing CPU Architecture type
[EXCAY2-41]: https://strongmind.atlassian.net/browse/EXCAY2-41?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Excay2 41     Improve ECS component for use with Identity Service

- deployment/src/strongmind_deployment/rails.py
- deployment/src/tests/test_rails.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/DEVOPS-13937)
Keep our Pulumi deployments up to date with what actually exists in AWS. AWS forcibly upgraded all our RDS instances to 15.4. We need pulumi to be aware.
Change 15.2 to 15.4
Deployed repo dashboard and journey tracker.
> 15.2 to 15.4 for RDS

- .github/workflows/docker-build.yml
[Link to Jira ticket](https://strongmind.atlassian.net/browse/DEVOPS-13565)
Allow docker to push max cached layers to ECR.
If a step in docker matches the SHA stored in ECR, that step will skipped during docker run in our CI. This should shorten our ECS deployments by a minute or so. 
Tested with repo dashboard https://github.com/StrongMind/repository-dashboard/tree/DEVOPS-13565
> Devops 13565 - Docker Cache in ECR

- deployment/src/strongmind_deployment/ecs.py
[[Link to Jira ticket](https://strongmind.atlassian.net/browse/TEAM-NUMBER)](https://strongmind.atlassian.net/browse/EXCAY2-111)
Do not pass the application the secret arn, but instead pass via ECS Secrets
Instead of using the environment variables for an ECS task, we should use the ECS Secrets.  
This involves setting a secret ARN for each configuration value,  and configuring the key in that secret that is used that should be passed to the container for that secret. ie: the valueFrom field.
secrets are in the task definition instead of the env variables
> Excay2 111 update secrets date type

- deployment/src/strongmind_deployment/autotag.py
- deployment/src/strongmind_deployment/operations.py
[EXCAY2-148](https://strongmind.atlassian.net/browse/EXCAY2-148)
* Generic code to facilitate configuring alarm actions with their opsgenie SNS Topics.
* Tag all resources with the owner tag
This pulls out some code from rails.py - however does not replace it - related to opsgenie SNS Topic configuration. 
In the same way, we are now parsing the `CODEOWNERS` file to get the team owner, and using that to resolve:
* `owner` tag
* sns topic
* `pulumi_aws.cloudwatch.MetricAlarm` config parameters
This was tested with the Identity service. 
[EXCAY2-148]: https://strongmind.atlassian.net/browse/EXCAY2-148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add OpsGenie convenience functions

- deployment/src/strongmind_deployment/execution.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/DEVOPS-14194)
If ecs migration fails, we want to retrieve cloudwatch logs.
We already had code that grabs the ecs task status
```
task = self.ecs_client.describe_tasks(
cluster=inputs['cluster'],
tasks=[task_id]
)
```
We just piggy back off of this check. See commit.
We forced the migration to 'fail', we received latest cloudwatch logs. 
Caveats:
We only get migration logs.
> get latest logs via boto3 if ecs task exitCode returns not 0.

- deployment/src/strongmind_deployment/container.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/devops-14567)
Grant course builder, and in turn all apps using this reusable component, access to Bedrock.
Adding minimal permissions needed, as defined by skunks, to the execution policy.
Will test and verify in stage course builder after deploy
> Adding bedrock InvokeModel and InvokeModelWithResponseStream to execution policy

- deployment/src/tests/mocks.py
This is done for usability when we need a mock that isn't supported, and speeds up finding out where you need to fix the problem.
[Link to Jira ticket](https://strongmind.atlassian.net/browse/EXCAY2-146)
When we need a mock for a pulumi call, we were getting confusing errors. We'd like to make the testing experience less confusing.
Add an exception that is thrown with descriptive text when we are calling an AWS pulumi method.
Tested in identity project
> Throw exception when mock type not found

- deployment/src/strongmind_deployment/container.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/devops-14748)
Update container cpu and memory defaults for Rails containers b/c containers are maxing memory and dying; many apps have already made the adjustment in main.
Update container cpu and memory defaults to 512 and 1028 respectively.
many apps have already made the adjustment in main.
> Update container cpu and memory defaults for Rails containers

- deployment/src/strongmind_deployment/cloudfront.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/devops-14874)
Added code to enable CORS with preflight to the IAC code for cloudfront. Deploys with cloudfront will now have CORS policy enabled.
Looked at pulumi documentation to find how to add CORS policy to the CloudFront Distribution Behaviour
Locally Deployed using pulumi to the stage environment. Before and after was tested to confirm if it works.
Before:
After (CORS is enabled):
> Update the IAC for cdn.strongmind.com to include the appropriate CORS policy

- deployment/src/strongmind_deployment/container.py
- deployment/src/tests/mocks.py
- deployment/src/tests/test_container.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/devops-14859)
- Add access logs to awsx load balancer
Looked at awsx documentation on how to activate access logs
Checked if access logs are enabled before and after running pulumi up
> Update PRW loadbalance to write access logs to s3 bucket.

- .github/workflows/send-deployment-notification.yml
- .github/workflows/send_deployment_notification.yml
BEL-3145: Create a reusable workflow to send the deployment time to repository-dashboard endpoint
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-3145)
We need a way to send deployment time to repo dashboard so that it can update the last deployed time. This reusable will send an authenticated request to repo dashboard which will update the time of when the last deploy was successfully ran
Get the current time
Get an auth token from identity (Create a new Client and API in login.strongmind.com and devlogin)
Send the payload and auth token to the repo dashboard /api/deployments endpoint
> BEL-3145: Create a reusable workflow to send the deployment time to repository-dashboard endpoint

- deployment/src/strongmind_deployment/container.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-3469)
I don't want to woken up by stage alarms at night. Stage environments are currently alarming to the Prod SNS topic. Create an empty stage SNS topic and route stage alarms to that.
Manually Create a SNS topic called "DevOps-Opsgenie-Stage".
Add an if condition to change sns_topic_arn to "DevOps-Opsgenie-Stage" if the stack is "stage".
Ran pytest to confirm the test case passes
> BEL-3469: Modify Public Resuable with If Condition on the Alarm for Stage

- deployment/src/strongmind_deployment/autoscale.py
- deployment/src/strongmind_deployment/container.py
- deployment/src/strongmind_deployment/rails.py
- deployment/src/strongmind_deployment/util.py
- deployment/src/tests/test_container_autoscaling.py
- docs/rails-app-deployment.md
[Link to Jira ticket](https://strongmind.atlassian.net/browse/bel-3356)
As a devops engineer, I should not be alerted by a healthy host metric alarm due to conflicts in code configuration.
Set a default desired count for number of web containers.
Set the min_capacity for web autoscaling to match desired count.
Turn on container insights for ECS clusters.
Create a new alarm based on RunningTaskCount which is now provided by container insights.
All tests pass.
Tested on tools using pulumi locally. -see screenshot below to verify that desired count is changed and running task alarm is created and container insights is turned on.
thub.com/user-attachments/assets/9441035a-ae51-44c0-8d5d-46ce15c0993c)
> Fix Healthy Host Metric Alarm

- deployment/src/strongmind_deployment/rails.py
- deployment/src/tests/mocks.py
- deployment/src/tests/test_rails.py
Central apparently doesn't run under load with only two containers.
Allow central to specify its web container count for now.
> BEL-3521 Bring back desired_web_count

- deployment/src/strongmind_deployment/alb.py
- deployment/src/strongmind_deployment/container.py
- deployment/src/strongmind_deployment/dashboard.py
- deployment/src/tests/mocks.py
- deployment/src/tests/test_container.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-3216)
The way we were using the awsx component to create the load balancer caused a listener on port 3000 to get created which got hit by bots and resulted in 5xx errors on our load balancer that alarmed.
Instead of using the pulumi.awsx component to create the load balancer, we are switching to use the component created by the Caylent team. This removes the "default target group" that created a listener pointed at port 3000.
We tested this change by rolling it out to multiple projects including frozen desserts, repository dashboard, and canvas-alerts-api-rails. 
Before
After
> BEL-3216 Switch to Alb component built by Caylent to remove listener on port 3000

- deployment/src/strongmind_deployment/container.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-3138)
Deployment does not work the first time because it depends on the fargate service already being available to set an autoscaling target. This was not the case.
Folks were turning autoscaling off, and then turning it back on again in order to make this work.
Specifying the dependency order fixes this problem.
Unable to do automated testing as Pulumi makes it impossible to test for dependency order through resource opts, so tested in staging enterprise canvas.
> BEL-3138 Fix autoscaling issues on creation.

- deployment/src/strongmind_deployment/rails.py
- deployment/src/tests/test_rails.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-3138)
Enterprise Canvas doesn't have REDIS_SERVER in the env and it needs the env variable to work
Set the REDIS_SERVER env variable in rails.py
pytest
> BEL-3138: Set REDIS_SERVER in the environment variable

- deployment/src/strongmind_deployment/container.py
- deployment/src/tests/test_container.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-3138)
Pulumi has deprecated .value and it's now changed to .content
Change .value to .content for cname_record and cert_validation
pytest
> BEL-3138: Change cname_record.value and cert_validation.value to .content

- .github/workflows/aws-deploy-with-pulumi.yml
- .github/workflows/aws-deploy.yml
- .github/workflows/docker-build.yml
[Link to Jira ticket](https://strongmind.atlassian.net/browse/bel-3524)
Keep pulumi state file in sync with prod
Run pulumi refresh during docker build.
Allow to temporarily bypass pulumi refresh with a pulumi-refresh input bool.
Can still pulumi refresh stage env at any time using pulumi-command in a stage deploy.
Called dev branch of prw using repo-dashboard and verified refresh ran during docker build and did not run when `pulumi-refresh: 'false'` was added to build.yml build job.
> Bel 3524 Deal with Pulumi Refresh Issue

- deployment/src/strongmind_deployment/dynamo.py
- deployment/src/strongmind_deployment/rails.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-3138)
When bringing down canvas-stage, it would try to delete DynamoDB and S3 bucket. However, these resources should be protected to avoid data loss.
Add protect=True for the resources
> BEL-3138: Protect DynamoDB and S3 Bucket

- .github/workflows/aws-deploy-with-pulumi.yml
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-3386)
- Running pulumi down from a github workflow causes it to error out as there is no VENV created.
> BEL-3386: Create a venv when running pulumi down.

- .github/workflows/docker-build.yml
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-3386)
We want to make it easier for devs to delete infrastructure if needed. We are refreshing stage in case the developer deletes protected resources manually in AWS.
Create a new job to refresh pulumi stage
> BEL-3386: Refresh pulumi stage when running docker build

- deployment/src/strongmind_deployment/alb.py
Fix the alb component b/c recent changes broke identity deploy
Fix AlbArgs to allow subnets to be optional with a default of none
No tests yet
> Fix AlbArgs to allow subnets to be optional with a default of none

- deployment/src/strongmind_deployment/container.py
Running task alarm is not reporting the runningtaskcount metric
Change the Namespace for the Running Task Alarm
Verified by pushing pulumi locally on repo dash
> Change the Namespace for the Running Task Alarm

- deployment/src/strongmind_deployment/container.py
- deployment/src/tests/test_container_autoscaling.py
Scale Rails apps web containers when traffic increases
Change the web container autoscaling metric to p99
Deployed pulumi locally on repo-dash, verified alarm configs
> Bel-3628 Change the Autoscaling Metric to p99

- deployment/src/strongmind_deployment/alb.py
- deployment/src/strongmind_deployment/container.py
- deployment/src/tests/mocks.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/bel-3198)
Route All Load Balancer Alarms to Teams
Add tags to alb component b/c new load balancers are not tagged
Use the operations.py file to get sns_topic_arn
Ran pulumi locally on repo-dashboard
Add tags to LB:
Route to team based on owning team:
> Bel 3198 Route All Load Balancer Alarms to Teams

- deployment/src/strongmind_deployment/container.py
- deployment/src/tests/test_container_autoscaling.py
Reverts StrongMind/public-reusable-workflows#166
This is breaking deployments. Will have to revisit.
> Revert "Bel 3937 Update Running Task Alarm to be based on Anomoly Detection "

- deployment/src/strongmind_deployment/rails.py
- deployment/src/tests/test_rails.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-3425)
Course builder was setting `worker_autoscale` but the code resulted in an error.
Set the values before passing the kwargs.
RSpec
> BEL-3425 Fix kwargs for autoscale

- deployment/src/strongmind_deployment/container.py
- deployment/src/tests/mocks.py
- deployment/src/tests/test_container_autoscaling.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/bel-4020)
Fix the web scaling alarms to use a better metric that will trigger autoscaling more quickly.
Update Web Autoscaling Alarms to use Target Response Time as the Metric.
We alarm and scale if the response time exceeds 5 seconds.
We scale one instance at a time if the response time is less than 10 and 3 instances if the response time is greater than 10s
We scale down one instance at a time, every 5 mins, once the response time drops below 5s.
Make sure tests pass.
Deployed locally to [repo-dash](https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#alarmsV2:alarm/repository-dashboard-prod-auto-scaling-out-alarm?~(search~'repository-dashboard))
> Bel-4020 Update Web Autoscaling Alarms to use Target Response Time as the Metric

- deployment/src/strongmind_deployment/container.py
- deployment/src/strongmind_deployment/rails.py
- deployment/src/tests/mocks.py
- deployment/src/tests/test_container.py
- deployment/src/tests/test_rails_worker.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/bel-4114)
Only allow 120% of containers for worker service during deployments
Added deployment_maximum_percent parameter to the fargate service in container.py
Added tests and tests pass
Deployed locally on repo-dash and verified config set in AWS
> Bel-4114 Set Deployment Maximum Percent to 120 for Worker Containers

- deployment/src/strongmind_deployment/container.py
- deployment/src/tests/test_container_autoscaling.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/Bel-4070)
Adjust alarm to use 100 as the threshold
Change the threshold to 100
Tests pass
Deployed locally on repo-dashboard
> Bel-4070-1 Change Running Task Alarm to use a threshold of 100

- deployment/src/strongmind_deployment/alb.py
- deployment/src/strongmind_deployment/container.py
- deployment/src/strongmind_deployment/dashboard.py
- deployment/src/strongmind_deployment/rails.py
- deployment/src/strongmind_deployment/redis.py
- deployment/src/strongmind_deployment/secrets.py
- deployment/src/strongmind_deployment/util.py
- deployment/src/strongmind_deployment/worker_autoscale.py
- deployment/src/tests/conftest.py
- deployment/src/tests/test_alb.py
- deployment/src/tests/test_container.py
- deployment/src/tests/test_container_autoscaling.py
- deployment/src/tests/test_dashboard.py
- deployment/src/tests/test_rails.py
- deployment/src/tests/test_redis.py
- deployment/src/tests/test_secrets.py
- deployment/src/tests/test_worker_container_autoscaling.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-3135)
So that we can use the RailsComponent several times in one project/stack, we need to be able to use a custom namespace throughout our stack.
Add a namespace attribute in all the relevant places.
Tested with unit tests and also ensured that repo dashboard did not change names.
> BEL-3135 multiple partners for canvas ECS

- .github/workflows/aws-deploy-with-pulumi.yml
- .github/workflows/aws-deploy.yml
Allow CICD for canvas to Canvas account
Add pulumi-bucket input
- Configure AWS login based on pulumi bucket
- Add id mapper envs
> BEL-3135 Allow pulumi bucket input for canvas deploy

- .github/workflows/rspec-test.yml
With parallel tests we don't always get the rspec_output.json which breaks our skipped test check.
Don't run skipped test check if we don't have that file.
> BEL-3173 Don't try to skip tests without output

- .github/workflows/rspec-test.yml
Trying manual install of docker for macos didn't work.
Go back to ubuntu for now.
> BEL-3173: Remove macos and docker step

- .github/workflows/rspec-test.yml
Noticed we were running specs on folders like "fixtures" that don't have any specs in them.
Check for specs and then skip remaining steps if there aren't any.
> BEL-3173: Don't run specs if there aren't any

- deployment/src/strongmind_deployment/container.py
- deployment/src/tests/test_container.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-3174)
Speed up deployments ( save 1.5 minutes on health checks ).
When we deploy, we're currently waiting 5 * 30 seconds to confirm a deployed container as good. In order to speed that up, we reduce it to 2 * 30 seconds.
Unit tested
> (B) BEL-3174 Speed up deployments

- deployment/src/strongmind_deployment/redis.py
- deployment/src/tests/test_redis.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-4477)
We are seeing redis run out of memory especially in canvas instances. volitile-lru will only evict keys with ttl previously set, but we expect all keys to be evicted if necessary.
Use allkeys-lru
Uncommented and adjusted unit test
> BEL-4477 Use allkeys-lru for cache redis

- deployment/src/strongmind_deployment/container.py
- deployment/src/strongmind_deployment/worker_autoscale.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-4546)
To allow autoscaling components to build on initial pulumi deploy
Add `opts=pulumi.ResourceOptions` with parent and depends on params to autoscaling resources
Deployed a test environment on repository-dashboard locally and verified good deploy with autoscale=true and worker_autoscale=true.
An initial subsequent deploy to existing infrastructure will tear down and rebuild autoscaling resources.
> Bel 4546 Allow Pulumi to Deploy Autoscaling Resources on Initial Deploys

- deployment/src/strongmind_deployment/worker_autoscale.py
- deployment/src/tests/test_worker_container_autoscaling.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-3136)
Scale canvas workers using the JobStaleness metric
Use correct metric_name if canvas instance is being deployed 
Added tests for metric_name
Verified locally with no breaking changes to repo-dashboard
> Bel 3136  add alarm for canvas autoscale

- deployment/src/strongmind_deployment/container.py
- deployment/src/strongmind_deployment/worker_autoscale.py
- deployment/src/tests/a_pulumi_containerized_app.py
- deployment/src/tests/mocks.py
- deployment/src/tests/test_container.py
- deployment/src/tests/test_container_autoscaling.py
- deployment/src/tests/test_worker_container_autoscaling.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-4546)
Allow canvas autoscaling
Change pulumi configuration to get the service id from ecs instead of predefining it - because we were reconstructing it before, rather than getting it, when we started building things with different cluster IDs, that failed.
Unit testing and pulumi previews.
> Bel 4546 Allow canvas autoscaling

- deployment/src/strongmind_deployment/container.py
- deployment/src/strongmind_deployment/rails.py
- deployment/src/tests/test_container.py
- deployment/src/tests/test_container_autoscaling.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-4567)
To allow the proper dimensions for canvas in the running task alarm
Because we were constructing the name and using the namespace we ended up doubling up the names for canvas components. Instead of using the namespace to guess what the cluster is called, we change to sending the actual cluster to the ContainerComponent. We also fixed the comparison_operator so that we will alarm when the threshold is met because we intended to alarm at 100 not 101
Unit test
> BEL-4567 Fix running task alarm for Canvas

- .github/workflows/rspec-test.yml
[Link to Jira ticket](https://strongmind.atlassian.net/browse/TH-1)
So that tests run in the test environment, and tests that use Sidekiq do not try to connect
to a real Redis server.
append `RAILS_ENV=test` to `bundle exec rspec` command
N/A
> (I) TH-1: Run rspec tests with RAILS_ENV=test

- .github/workflows/dotnet-build.yml
Replaced outdated actions with 'actions/upload-artifact@v4' in workflows.
> Update workflows to use actions/upload-artifact@v4

- .github/workflows/dev_upload_interactives.yml
- .github/workflows/prod_upload_interactives.yml
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-4757)
Fix broken pipelines for Interactives
All interactive repos will now use these workflows once the `modify-github-workflows-replace-workflows.py` script in Helpers repo is run which will update all interactives repos' workflows
The `az storage blob upload batch` cli command requires the copy library and this is now broken b/c MS moved its CDN from edge to front door and the `storage blob` command apparently is still trying to download the `copy` library from the old CDN. from https://github.com/Azure/azure-cli/issues/30635
Add new workflows, which includes changes to remove the broken action and replace with new action
Use new action to use the cli directly and install the copy library before calling the storage blob …
> BEL-4757 Add new workflows for interactives

- deployment/src/strongmind_deployment/container.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-4831)
This change prevents deployments from resetting scaling.
Update the deployment logic to ignore changes to the desired count of ECS containers. 
Josh ran with repo dashboard.
> BEL-4831: Fix issue of ECS deployments resetting desired count of containers

- deployment/src/strongmind_deployment/container.py
- deployment/src/tests/test_container.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-5414)
FIx issue of users getting blocked, probably due to invalid sessions and cloudfront allowing http requests
Change policy to force redirect to https
Manually changed distribution for course-builder prod and users were unable to replicate issue afterwards
> BEL-5414 Ensure that every request is forced to use HTTPS end to end

- deployment/src/strongmind_deployment/container.py
- deployment/src/strongmind_deployment/rails.py
- deployment/src/tests/test_rails.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-5363)
- Dynamically retrieve the desired task count from AWS to ensure accurate scaling and resource allocation.
- Resolve edge cases in the namespace implementation that caused the initial implementation to fail, ensuring more robust and reliable workflows.
This pull request includes multiple changes to the `deployment/src/strongmind_deployment` and `deployment/src/tests` directories to improve the setup and testing of load balancers and ECS services. The most important changes include refactoring the `setup_load_balancer` method, adding error handling for ECS service discovery, and updating the test cases to reflect these changes.
* [`deployment/src/strongmind_deployment/container.py`](diffhunk://#diff-3f9fe040f3ced4b63cc3 …
> Bel-5363 Fix Problem Getting Desired Count Dynamically

- deployment/src/strongmind_deployment/container.py
- deployment/src/tests/test_container_autoscaling.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-4179)
This pull request introduces the implementation of a scheduled scaling feature in the `ContainerComponent` class, along with corresponding validation and testing. The most important changes include adding new parameters for scheduled scaling, implementing validation methods, and creating scheduled scaling actions. Additionally, tests have been added to ensure the correct functionality of this new feature.
* Added new parameters to the `__init__` method of the `ContainerComponent` class for scheduled scaling, including `scheduled_scaling`, `pre_scale_time`, `post_scale_time`, and `peak_min_capacity`. [[1]](diffhunk://#diff-3f9fe040f3ced4b63cc35de46baf666b286eafbe36691e7301da52ed109e1de7R42-R46) …
> BEL-4179: Implement scheduled scaling feature

- deployment/requirements.txt
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-6207)
Fix Issue with PRW - AttributeError: 'Record' object has no attribute 'hostname'
Pin pulumi-cloudflare to 5.49.1 to prevent breaking changes in 6.0.0
Ran test locally and verified
> BEL-6207 Pin pulumi-cloudflare to 5.49.1 

- deployment/requirements.txt
- deployment/src/strongmind_deployment/container.py
- deployment/src/tests/mocks.py
- deployment/src/tests/test_container.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-5424)
Allow PRW to supoort multiple cnames.
This branch will create the cnames for the cloudfront distribution. 
Additional config is needed for the load balancer. 
**I had to pin pulumi to an older version because some tests are currently broken on the newest version -- will need to address in the not-so-distant-future**
This pull request introduces several enhancements and refactors to the `strongmind_deployment` module, particularly focusing on improving the handling of additional domain aliases in CloudFront distributions and their corresponding validation records. The changes also include updates to the associated tests to ensure the new functionalities are properly validated.
* **Additional Domain Aliases:**
* …
> Bel-5424: support multiple cnames

- .github/workflows/rspec-test.yml
[Link to Jira ticket](https://strongmind.atlassian.net/browse/RD-1091)
Optimize test runs by splitting out request and lib specs (longest running in course-builder).
- Refactor file distribution logic to enhance test execution speed by organizing spec files into distinct folders.
- Create a function to handle file distribution for models, requests, and services
- Split files into four separate directories based on their count
- Ensure empty directories are handled gracefully
Ran script locally.
> RD-1091: Speed up test runs by splitting requests and lib folders into separate directories

- deployment/src/strongmind_deployment/container.py
- deployment/src/tests/test_container.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-16970)
[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-16971)
Currently, alarms are triggered when 25% of containers are unhealthy. However, for applications that scale down to as few as 2 containers, a single unhealthy container can incorrectly trigger an alarm—even though the system automatically scales up and handles the load without intervention. To avoid unnecessary alerts in these low-capacity scenarios, we should only trigger an alarm if 2 or more containers are unhealthy when the total number is less than 5. For services with 5 or more containers, the existing 25% threshold remains appropriate.
Modify the unhealthy host metric alarm expression to apply different logic based on the number of …
> QTY-16970: Refine Unhealthy Host Metric Expression

- .github/workflows/rspec-test.yml
Make our builds not fail downloading a script that isn't even running.
Remove script.
> Remove codeclimate and skipped test nanny from build

- deployment/src/strongmind_deployment/lambda_component.py
- Updated the constructor of LambdaEnvVariables to allow values as Pulumi Outputs.
- Enhanced validation to ensure environment variable values can be strings or Pulumi Outputs.
- Improved type hinting for better clarity and maintainability.
> (B) NXT-7108: Refine LambdaEnvVariables to accept Pulumi Outputs

- deployment/src/strongmind_deployment/container.py
[Link to Jira ticket](https://strongmind.atlassian.net/browse/EXP1-6597)
This pull request adds support for custom port mappings to the container initialization logic, allowing users to explicitly specify port mapping configurations. The changes ensure that if custom port mappings are provided, they will override the automatic port mapping behavior.
This is needed so we can allow the dagster daemon and user-code services to communicate with each other within the vpc after having enabled the service discovery for each.
Container configuration improvements:
* Added a new `port_mappings` parameter to the `__init__` method of the `Container` class, allowing users to specify custom port mappings as a list of `awsx.ecs.TaskDefinitionPortMappingArgs`.
* Updated the port mapping logic in …
> (B) EXP1-6597: Enhance container component
